apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      volumes:
        - name: tasks-api-volume
          hostPath:
            path: /tasks
            type: DirectoryOrCreate
      containers:
      - name: tasks-api
        image: othbel/tasks-api:1.0.0
        env:
          - name: AUTH_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: project-env
                key: TASKS_AUTH_ADDRESS
        volumeMounts:
          - mountPath: /app/tasks
            name: tasks-api-volume
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
